CREATE DATABASE IF NOT EXISTS multapps_dev;
USE multapps_dev;

CREATE TABLE IF NOT EXISTS categoria (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR (100) NOT NULL,
data_criacao TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
data_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
status ENUM ('inativo','ativo','excluido') NOT NULL

);


CREATE TABLE IF NOT EXISTS  produtos (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
categoria_id INT NOT NULL,
nome VARCHAR (100) NOT NULL,
preco DECIMAL NOT NULL,
descricao VARCHAR (1000) NOT NULL,
estoque VARCHAR (1000) NOT NULL,
data_criacao TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
data_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
status BIT NOT NULL,

	FOREIGN KEY(categoria_id) REFERENCES categoria(id)
);


CREATE TABLE IF NOT EXISTS  usuario (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR (100) NOT NULL,
cpf VARCHAR (11) NOT NULL UNIQUE,
senha VARCHAR (100) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
data_criacao TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
data_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
data_ultimo_acesso DATETIME,
status BIT NOT NULL
);
